# Generated by Django 3.1.7 on 2021-03-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountPrimeNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(verbose_name='Limit')),
                ('counter', models.IntegerField(verbose_name='Counter')),
            ],
        ),
    ]
