# Generated by Django 3.1.7 on 2021-03-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210317_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='countprimenumbers',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Failure'), (2, 'Received'), (3, 'Started'), (4, 'Success')], default=0),
        ),
    ]
